fixed: apbs-mem-potential --template failed
- raised exception

     TypeError: _populate_default() takes exactly 2 arguments (1 given)

- made nomembrane in bpio.RunParameters._populate_default() a kwarg instead of
  arg (probably an issue due to the patching with zero-mem code... and absence
  of any tests)